// tslint:disable
/**
 * The Butterfly-API
 * The butterfly is a game/simulation model that is based on the Butterfly effect on human decision making modelled as ANNs, The project is inspired by the likes of Life is Strange Series , Until Dawn and is a going to have a DnD styled interface. This current API provides various game flows and models to create a simulation model or game of your own
 *
 * OpenAPI spec version: 1.0
 * Contact: dantraztrev@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
